### ISSUE TITLE
Implementar Formatador

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/potigol#2]
Discussão base: https://github.com/orgs/potigol/discussions/63#discussioncomment-9330921
Implementação anterior baseada em ANTLR: https://github.com/potigol/EditorPotigol/blob/master/src/main/scala/br/edu/ifrn/potigol/editor/PrettyListener.java

**Comment by Aristidescosta** [comment]
@leonelsanchesdasilva  já tem uma boa implementação do formatador. É para dar sequência??

**Comment by leonelsanchesdasilva** [comment]
@Aristidescosta Não, eu estava a ajustar ontem. Por isso mantive a issue aberta esse tempo.
